(function($){function elegantPopup(config){var config=config||{},slidein=set_default(config.slideinhtml,''),join=set_default(config.joinhtml,''),offer=set_default(config.offerhtml,'');flyin=set_default(config.flyinhtml,''),popup=set_default(config.popuphtml,''),cookieExpire=config.cookieExpire||5500,autospeed=config.autospeed||10000,flyinAutospeed=config.flyinAutospeed||3000,offer_time_30=1800,offer_time_180=10800,offer_time_1440=86400,pathname=window.location.pathname,cookies=get_cookies(),popup_viewed_cookie='popup_viewed',offer_end_cookie='offer_end',offer_start_cookie='offer_start',offer_last_chance_cookie='offer_last_chance',flyin_status_cookie='flyin_status',slidein_status_cookie='slidein_status',join_status_cookie='join_status',joined_cookie='joined',subscribed_cookie='subscribed_2',popup_viewed=cookies[popup_viewed_cookie],offer_end=cookies[offer_end_cookie],offer_start=cookies[offer_start_cookie],offer_last_chance=cookies[offer_last_chance_cookie],flyin_status=cookies[flyin_status_cookie],slidein_status=cookies[slidein_status_cookie],join_status=cookies[join_status_cookie],joined=cookies[joined_cookie],subscribed=cookies[subscribed_cookie],click_source=getParameterByName('utm_medium');if(pathname.includes('/blog/divi-resources')){var active_promo='divi';}else if(pathname.includes('/blog')){var active_promo='blog';}else if(pathname.includes('/members-area')){var active_promo='members';}else{var active_promo='discount';}
if(pathname.includes('/register')){var offer_time=offer_time_180,enable_offer='true';}else if(pathname.includes('/discount')){var offer_time=offer_time_1440,enable_offer='true';}
if(pathname.includes('/register')||pathname.includes('/renew')||pathname.includes('/checkout')||pathname.includes('/discount')||pathname.includes('/black-friday')||pathname.includes('/cyber-monday')||pathname.includes('/join')||pathname.includes('/preview')||pathname.includes('-complete/')){var disable_promo='true';}
if(pathname.includes('-complete/')){set_cookie(joined_cookie,'true','true');set_cookie(join_status_cookie,'closed','true');}
if(pathname.includes('/members-area/')){var members_area='true';}
if(pathname.includes('/join')){set_cookie(join_status_cookie,'open','true');}
if(active_promo=='divi'){var flyin=set_default(config.divi_flyinhtml,''),popup=set_default(config.divi_popuphtml,'');}else if(active_promo=='blog'){var flyin=set_default(config.blog_flyinhtml,''),popup=set_default(config.blog_popuphtml,'');}else if(active_promo=='members'){var flyin=set_default(config.members_flyinhtml,''),popup=set_default(config.members_popuphtml,'');}
if(!offer_end&&!joined&&enable_offer=='true'){var current_time=$.now();set_cookie(offer_start_cookie,current_time,'true');set_cookie(offer_end_cookie,offer_time,'true');var timer=offer_time;}else{var current_time=$.now(),used_time=(current_time-offer_start)/1000,timer=offer_end-used_time;if(offer_end-used_time<=0){var offer_expired='true';}}
if($('#limited-offer-countdown').length){$('#limited-offer-countdown').countdown({until:timer,onExpiry:end_countdown,onTick:callbacks,format:'HMS'});}
if(pathname=='/discount/today/'&&offer_expired){if(offer_last_chance=='false'){window.location.href='https://www.elegantthemes.com/join/';}else{$('#countdown-popup').show();}}
$('#countdown-popup .button').on('click',function(){extend_offer();});if(!slidein_status){set_cookie(slidein_status_cookie,'open','true');slidein_status=get_cookie(slidein_status_cookie);}
if(!flyin_status){set_cookie(flyin_status_cookie,'open','true');}
if(!disable_promo&&join_status==='open'&&!joined&&!members_area&&(!timer||offer_expired)){fire_join();}
if(!disable_promo&&slidein_status==='open'&&join_status!='open'&&!joined&&(!timer||offer_expired)){fire_slidein();}
if(!disable_promo&&!popup_viewed&&click_source!='email'&&(slidein_status!='open'||joined)&&!subscribed&&(!timer||offer_expired||joined)){setTimeout(function(){if(popup_viewed==='true'){return;}
fire_popup();},autospeed);}
if(!disable_promo&&!subscribed&&popup_viewed&&(slidein_status!='open'||joined)&&(!timer||offer_expired||joined)){if(flyin_status==='closed'){flyinAutospeed=0;}
setTimeout(function(){fire_flyin();},flyinAutospeed);}
if(!disable_promo&&!joined&&offer_end&&!offer_expired&&!members_area){fire_offer();}
function fire_slidein(){$("body").prepend(slidein);$("body").addClass('with_promo_slide_in');$('.promo-slide-in .button').on('click',function(){disable_slidein();});$('.promo-slide-in-close-promo').on('click',function(){disable_slidein();$("body").removeClass('with_promo_slide_in');$("body").addClass('without_promo_slide_in');$('.promo-slide-in').addClass("promo-slide-in-closed").delay(299).queue(function(next){$(this).hide();});});}
function fire_join(){$("body").prepend(join);$("body").addClass('with_promo_slide_in');$('.promo-slide-in-close-promo').on('click',function(){disable_join();disable_slidein();$("body").removeClass('with_promo_slide_in');$("body").addClass('without_promo_slide_in');$('.promo-slide-in').addClass("promo-slide-in-closed").delay(299).queue(function(next){$(this).hide();});});}
function fire_offer(){if($('.et_cookie_consent').length){return;}
$("body").append(offer);$('#limited-offer-countdown').countdown({until:timer,onExpiry:end_countdown,onTick:callbacks,format:'HMS'});}
function fire_popup(){if($('.et_cookie_consent').length){return;}
$("body").append(popup);$("#exitpopup").show();disable_popup();$('#exit_subscribe').on('click',function(){subscribe();});$('.exit-button').on('click',function(){$("#exitpopup").hide();});$(".exit-button").hover(function(){$(".exit_warning").fadeIn(200);},function(){$(".exit_warning").fadeOut(200);});}
function fire_flyin(){if($('.et_cookie_consent').length){return;}
var flyin_status=get_cookie(flyin_status_cookie);$("body").append(flyin);if(flyin_status==='closed'){$('#flyinwrapper').addClass("minimize stopanimate");}else{$('#flyinwrapper').removeClass("minimize");}
$('.exit-button').on('click',function(){$('#flyinwrapper').addClass("minimize");minimize_flyin();});$('#flying_subscribe').on('click',function(){subscribe();});$('.flyinbutton').on('click',function(){$('#flyinwrapper').removeClass("minimize");minimize_flyin();});}
function callbacks(periods){if($.countdown.periodsToSeconds(periods)<=0){end_countdown();}}
function end_countdown(){$('#flyin').remove();$('#countdown-popup').show();}
function extend_offer(){var current_time=$.now();set_cookie(offer_last_chance_cookie,'false','true');set_cookie(offer_start_cookie,current_time,'true');set_cookie(offer_end_cookie,offer_time_30,'true');location.reload(true);}
function disable_popup(){set_cookie(popup_viewed_cookie,'true','true');}
function disable_slidein(){set_cookie(slidein_status_cookie,'closed','true');}
function disable_join(){set_cookie(join_status_cookie,'closed','true');}
function subscribe(){set_cookie(subscribed_cookie,'true','true');}
function minimize_flyin(){var flyin_status=get_cookie(flyin_status_cookie);if(flyin_status==='open'){set_cookie(flyin_status_cookie,'closed','true');}else{set_cookie(flyin_status_cookie,'open','true');}}
function set_default(_property,_default){return typeof _property==='undefined'?_default:_property;}
function set_cookie(cookieName,value,setExpire){Cookies.remove(cookieName);if(setExpire==='false'){Cookies.set(cookieName,value,{path:'/'});}else{Cookies.set(cookieName,value,{expires:cookieExpire,path:'/'});}}
function getParameterByName(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?&]"+name+"=([^&#]*)"),results=regex.exec(location.search)
return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "));}
function get_cookies(){var document_cookies=document.cookie.split('; ').reduce(function(prev,curr){var el=curr.split('=');prev[el[0]]=el[1];return prev;},{});return document_cookies;}
function get_cookie(name){var value="; "+document.cookie,parts=value.split("; "+name+"=")
if(parts.length==2)return parts.pop().split(";").shift();}};$(document).ready(function(){var _elegantPopup=elegantPopup({popuphtml:'',members_popuphtml:'',divi_popuphtml:'',blog_popuphtml:'',flyinhtml:'',members_flyinhtml:'',
divi_flyinhtml:'',blog_flyinhtml:'',slideinhtml:'<div class="promo-slide-in accent-pink card-featured"><div class="promo-slide-in-content"><div class="promo-slide-in-content-inner"><h6>Log in to get Ad-free tools, <span>Access upcoming tools &amp; Access premium features</span></h6> <a class="button inline-button" href="/gallery/divi/">Learn More</a></div></div><div class="promo-slide-in-close-promo"></div></div>',joinhtml:'<div class="promo-slide-in accent-blue gradient-background-green"><div class="promo-slide-in-content"><div class="promo-slide-in-content-inner"><h6><img class="promo-slide-in-icon" src="/images/icons/guarantee-icon.png" width="20" height="28" alt="Guarantee" />Risk Free For 30 Days <span>When You Join Today!</span></h6> <a class="button inline-button" href="/join/">Join Today</a></div></div><div class="promo-slide-in-close-promo"></div></div>',offerhtml:'',});});})(jQuery)
