  (function($){function elegantPopup(config){var config=config||{},slidein=set_default(config.slideinhtml,&#39;&#39;),join=set_default(config.joinhtml,&#39;&#39;),offer=set_default(config.offerhtml,&#39;&#39;);flyin=set_default(config.flyinhtml,&#39;&#39;),popup=set_default(config.popuphtml,&#39;&#39;),cookieExpire=config.cookieExpire||5500,autospeed=config.autospeed||10000,flyinAutospeed=config.flyinAutospeed||3000,offer_time_30=1800,offer_time_180=10800,offer_time_1440=86400,pathname=window.location.pathname,cookies=get_cookies(),popup_viewed_cookie=&#39;popup_viewed&#39;,offer_end_cookie=&#39;offer_end&#39;,offer_start_cookie=&#39;offer_start&#39;,offer_last_chance_cookie=&#39;offer_last_chance&#39;,flyin_status_cookie=&#39;flyin_status&#39;,slidein_status_cookie=&#39;slidein_status&#39;,join_status_cookie=&#39;join_status&#39;,joined_cookie=&#39;joined&#39;,subscribed_cookie=&#39;subscribed_2&#39;,popup_viewed=cookies[popup_viewed_cookie],offer_end=cookies[offer_end_cookie],offer_start=cookies[offer_start_cookie],offer_last_chance=cookies[offer_last_chance_cookie],flyin_status=cookies[flyin_status_cookie],slidein_status=cookies[slidein_status_cookie],join_status=cookies[join_status_cookie],joined=cookies[joined_cookie],subscribed=cookies[subscribed_cookie],click_source=getParameterByName(&#39;utm_medium&#39;);if(pathname.includes(&#39;/blog/divi-resources&#39;)){var active_promo=&#39;divi&#39;;}else if(pathname.includes(&#39;/blog&#39;)){var active_promo=&#39;blog&#39;;}else if(pathname.includes(&#39;/members-area&#39;)){var active_promo=&#39;members&#39;;}else{var active_promo=&#39;discount&#39;;}
if(pathname.includes(&#39;/register&#39;)){var offer_time=offer_time_180,enable_offer=&#39;true&#39;;}else if(pathname.includes(&#39;/discount&#39;)){var offer_time=offer_time_1440,enable_offer=&#39;true&#39;;}
if(pathname.includes(&#39;/register&#39;)||pathname.includes(&#39;/renew&#39;)||pathname.includes(&#39;/checkout&#39;)||pathname.includes(&#39;/discount&#39;)||pathname.includes(&#39;/black-friday&#39;)||pathname.includes(&#39;/cyber-monday&#39;)||pathname.includes(&#39;/join&#39;)||pathname.includes(&#39;/preview&#39;)||pathname.includes(&#39;-complete/&#39;)){var disable_promo=&#39;true&#39;;}
if(pathname.includes(&#39;-complete/&#39;)){set_cookie(joined_cookie,&#39;true&#39;,&#39;true&#39;);set_cookie(join_status_cookie,&#39;closed&#39;,&#39;true&#39;);}
if(pathname.includes(&#39;/members-area/&#39;)){var members_area=&#39;true&#39;;}
if(pathname.includes(&#39;/join&#39;)){set_cookie(join_status_cookie,&#39;open&#39;,&#39;true&#39;);}
if(active_promo==&#39;divi&#39;){var flyin=set_default(config.divi_flyinhtml,&#39;&#39;),popup=set_default(config.divi_popuphtml,&#39;&#39;);}else if(active_promo==&#39;blog&#39;){var flyin=set_default(config.blog_flyinhtml,&#39;&#39;),popup=set_default(config.blog_popuphtml,&#39;&#39;);}else if(active_promo==&#39;members&#39;){var flyin=set_default(config.members_flyinhtml,&#39;&#39;),popup=set_default(config.members_popuphtml,&#39;&#39;);}
if(!offer_end&amp;&amp;!joined&amp;&amp;enable_offer==&#39;true&#39;){var current_time=$.now();set_cookie(offer_start_cookie,current_time,&#39;true&#39;);set_cookie(offer_end_cookie,offer_time,&#39;true&#39;);var timer=offer_time;}else{var current_time=$.now(),used_time=(current_time-offer_start)/1000,timer=offer_end-used_time;if(offer_end-used_time&lt;=0){var offer_expired=&#39;true&#39;;}}
if($(&#39;#limited-offer-countdown&#39;).length){$(&#39;#limited-offer-countdown&#39;).countdown({until:timer,onExpiry:end_countdown,onTick:callbacks,format:&#39;HMS&#39;});}
if(pathname==&#39;/discount/today/&#39;&amp;&amp;offer_expired){if(offer_last_chance==&#39;false&#39;){window.location.href=&#39;https://www.elegantthemes.com/join/&#39;;}else{$(&#39;#countdown-popup&#39;).show();}}
$(&#39;#countdown-popup .button&#39;).on(&#39;click&#39;,function(){extend_offer();});if(!slidein_status){set_cookie(slidein_status_cookie,&#39;open&#39;,&#39;true&#39;);slidein_status=get_cookie(slidein_status_cookie);}
if(!flyin_status){set_cookie(flyin_status_cookie,&#39;open&#39;,&#39;true&#39;);}
if(!disable_promo&amp;&amp;join_status===&#39;open&#39;&amp;&amp;!joined&amp;&amp;!members_area&amp;&amp;(!timer||offer_expired)){fire_join();}
if(!disable_promo&amp;&amp;slidein_status===&#39;open&#39;&amp;&amp;join_status!=&#39;open&#39;&amp;&amp;!joined&amp;&amp;(!timer||offer_expired)){fire_slidein();}
if(!disable_promo&amp;&amp;!popup_viewed&amp;&amp;click_source!=&#39;email&#39;&amp;&amp;(slidein_status!=&#39;open&#39;||joined)&amp;&amp;!subscribed&amp;&amp;(!timer||offer_expired||joined)){setTimeout(function(){if(popup_viewed===&#39;true&#39;){return;}
fire_popup();},autospeed);}
if(!disable_promo&amp;&amp;!subscribed&amp;&amp;popup_viewed&amp;&amp;(slidein_status!=&#39;open&#39;||joined)&amp;&amp;(!timer||offer_expired||joined)){if(flyin_status===&#39;closed&#39;){flyinAutospeed=0;}
setTimeout(function(){fire_flyin();},flyinAutospeed);}
if(!disable_promo&amp;&amp;!joined&amp;&amp;offer_end&amp;&amp;!offer_expired&amp;&amp;!members_area){fire_offer();}
function fire_slidein(){$(&quot;body&quot;).prepend(slidein);$(&quot;body&quot;).addClass(&#39;with_promo_slide_in&#39;);$(&#39;.promo-slide-in .button&#39;).on(&#39;click&#39;,function(){disable_slidein();});$(&#39;.promo-slide-in-close-promo&#39;).on(&#39;click&#39;,function(){disable_slidein();$(&quot;body&quot;).removeClass(&#39;with_promo_slide_in&#39;);$(&quot;body&quot;).addClass(&#39;without_promo_slide_in&#39;);$(&#39;.promo-slide-in&#39;).addClass(&quot;promo-slide-in-closed&quot;).delay(299).queue(function(next){$(this).hide();});});}
function fire_join(){$(&quot;body&quot;).prepend(join);$(&quot;body&quot;).addClass(&#39;with_promo_slide_in&#39;);$(&#39;.promo-slide-in-close-promo&#39;).on(&#39;click&#39;,function(){disable_join();disable_slidein();$(&quot;body&quot;).removeClass(&#39;with_promo_slide_in&#39;);$(&quot;body&quot;).addClass(&#39;without_promo_slide_in&#39;);$(&#39;.promo-slide-in&#39;).addClass(&quot;promo-slide-in-closed&quot;).delay(299).queue(function(next){$(this).hide();});});}
function fire_offer(){if($(&#39;.et_cookie_consent&#39;).length){return;}
$(&quot;body&quot;).append(offer);$(&#39;#limited-offer-countdown&#39;).countdown({until:timer,onExpiry:end_countdown,onTick:callbacks,format:&#39;HMS&#39;});}
function fire_popup(){if($(&#39;.et_cookie_consent&#39;).length){return;}
$(&quot;body&quot;).append(popup);$(&quot;#exitpopup&quot;).show();disable_popup();$(&#39;#exit_subscribe&#39;).on(&#39;click&#39;,function(){subscribe();});$(&#39;.exit-button&#39;).on(&#39;click&#39;,function(){$(&quot;#exitpopup&quot;).hide();});$(&quot;.exit-button&quot;).hover(function(){$(&quot;.exit_warning&quot;).fadeIn(200);},function(){$(&quot;.exit_warning&quot;).fadeOut(200);});}
function fire_flyin(){if($(&#39;.et_cookie_consent&#39;).length){return;}
var flyin_status=get_cookie(flyin_status_cookie);$(&quot;body&quot;).append(flyin);if(flyin_status===&#39;closed&#39;){$(&#39;#flyinwrapper&#39;).addClass(&quot;minimize stopanimate&quot;);}else{$(&#39;#flyinwrapper&#39;).removeClass(&quot;minimize&quot;);}
$(&#39;.exit-button&#39;).on(&#39;click&#39;,function(){$(&#39;#flyinwrapper&#39;).addClass(&quot;minimize&quot;);minimize_flyin();});$(&#39;#flying_subscribe&#39;).on(&#39;click&#39;,function(){subscribe();});$(&#39;.flyinbutton&#39;).on(&#39;click&#39;,function(){$(&#39;#flyinwrapper&#39;).removeClass(&quot;minimize&quot;);minimize_flyin();});}
function callbacks(periods){if($.countdown.periodsToSeconds(periods)&lt;=0){end_countdown();}}
function end_countdown(){$(&#39;#flyin&#39;).remove();$(&#39;#countdown-popup&#39;).show();}
function extend_offer(){var current_time=$.now();set_cookie(offer_last_chance_cookie,&#39;false&#39;,&#39;true&#39;);set_cookie(offer_start_cookie,current_time,&#39;true&#39;);set_cookie(offer_end_cookie,offer_time_30,&#39;true&#39;);location.reload(true);}
function disable_popup(){set_cookie(popup_viewed_cookie,&#39;true&#39;,&#39;true&#39;);}
function disable_slidein(){set_cookie(slidein_status_cookie,&#39;closed&#39;,&#39;true&#39;);}
function disable_join(){set_cookie(join_status_cookie,&#39;closed&#39;,&#39;true&#39;);}
function subscribe(){set_cookie(subscribed_cookie,&#39;true&#39;,&#39;true&#39;);}
function minimize_flyin(){var flyin_status=get_cookie(flyin_status_cookie);if(flyin_status===&#39;open&#39;){set_cookie(flyin_status_cookie,&#39;closed&#39;,&#39;true&#39;);}else{set_cookie(flyin_status_cookie,&#39;open&#39;,&#39;true&#39;);}}
function set_default(_property,_default){return typeof _property===&#39;undefined&#39;?_default:_property;}
function set_cookie(cookieName,value,setExpire){Cookies.remove(cookieName);if(setExpire===&#39;false&#39;){Cookies.set(cookieName,value,{path:&#39;/&#39;});}else{Cookies.set(cookieName,value,{expires:cookieExpire,path:&#39;/&#39;});}}
function getParameterByName(name){name=name.replace(/[\[]/,&quot;\\[&quot;).replace(/[\]]/,&quot;\\]&quot;);var regex=new RegExp(&quot;[\\?&amp;]&quot;+name+&quot;=([^&amp;#]*)&quot;),results=regex.exec(location.search)
return results===null?&quot;&quot;:decodeURIComponent(results[1].replace(/\+/g,&quot; &quot;));}
function get_cookies(){var document_cookies=document.cookie.split(&#39;; &#39;).reduce(function(prev,curr){var el=curr.split(&#39;=&#39;);prev[el[0]]=el[1];return prev;},{});return document_cookies;}
function get_cookie(name){var value=&quot;; &quot;+document.cookie,parts=value.split(&quot;; &quot;+name+&quot;=&quot;)
if(parts.length==2)return parts.pop().split(&quot;;&quot;).shift();}};$(document).ready(function(){var _elegantPopup=elegantPopup({popuphtml:&#39;&#39;,members_popuphtml:&#39;&#39;,divi_popuphtml:&#39;&#39;,blog_popuphtml:&#39;&#39;,flyinhtml:&#39;&#39;,members_flyinhtml:&#39;&#39;,
divi_flyinhtml:&#39;&#39;,blog_flyinhtml:&#39;&#39;,slideinhtml:&#39;<div class='promo-slide-in accent-pink card-featured'><div class='promo-slide-in-content'><div class='promo-slide-in-content-inner'><h6>Divi Changes Everything. <span>Give It A Test Drive!</span></h6> <a class='button inline-button' href='/gallery/divi/'>Learn More</a></div></div><div class='promo-slide-in-close-promo'/></div>&#39;,joinhtml:&#39;<div class='promo-slide-in accent-blue gradient-background-green'><div class='promo-slide-in-content'><div class='promo-slide-in-content-inner'><h6><img alt='Guarantee' class='promo-slide-in-icon' height='28' src='/images/icons/guarantee-icon.png' width='20'/>Risk Free For 30 Days <span>When You Join Today!</span></h6> <a class='button inline-button' href='/join/'>Join Today</a></div></div><div class='promo-slide-in-close-promo'/></div>&#39;,offerhtml:&#39;&#39;,});});})(jQuery)
